M48
; DRILL file {KiCad (6.0.2)} date Thu Jul 14 16:33:31 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-07-14T16:33:31+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
%
G90
G05
T1
X173.75Y-71.23
X175.5Y-83.505
X184.75Y-70.985
X199.0Y-109.515
T0
M30
