M48
; DRILL file {KiCad (6.0.2)} date Thu Jul 14 16:29:56 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-07-14T16:29:56+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.750
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.050
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X125.95Y-102.25
X168.55Y-102.25
X175.2Y-102.178
X217.8Y-102.178
T2
X237.5Y-102.974
X251.5Y-102.974
T3
X264.0Y-103.825
X273.0Y-103.825
T0
M30
